### ISSUE TITLE
Cacti 1.1.31 new graph error

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1244]
After create a new graph (local linux machine) rrd and graph doesn't create. 
And in log file I see errors about another one template:

20-Jan-2018 08:22:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_CCX.php: 18 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
--
20-Jan-2018 08:22:01 - ERROR PHP NOTICE: Undefined offset: 3 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_CCX.php on line: 18
20-Jan-2018 08:22:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_CCX.php: 17 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
20-Jan-2018 08:22:01 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_CCX.php on line: 17
20-Jan-2018 08:22:01 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_CCX.php: 16 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
20-Jan-2018 08:22:01 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_CCX.php on line: 16

p.s. in Cacti 1.129 all worked good

**Comment by netniV** [comment]
This new graph is to an existing device? Or a new device?  The output suggests that there is no output coming back from your scripts.  That in turn suggests that they are not working properly or getting an error. 

Try running the scripts manually at the command line. Do you see output there?

**Comment by Izmenoff** [comment]
After update cacri to ver 1.1,31 all existing devices with Linux servers has stopped displaying graphs. In the network devices all's fine.  If I create new device and new graphs, cacti does not record new rrd files. Premission on RRD folder is ok

**Comment by netniV** [comment]
Try running the scripts manually at the command line. Do you see output there?

**Comment by Izmenoff** [comment]
what kind of script? can you help me with full string of script?

**Comment by netniV** [comment]
There are two modes.  run the script directly:
```
cd /var/www/html/cacti/
php scripts/ss_host_disk.php 'srv-omi-01' '366' '2:161:500:1:40:public::::::' 'get' 'used' '6'
```

Secondly, if the above appears right, run the script via script server
```
cd /var/www/html/cacti
php -q script_server.php
```
Once that says ready, paste in
```
/var/www/html/cacti/scripts/ss_host_disk.php 'srv-omi-01' '366' '2:161:500:1:40:public::::::' 'get' 'used' '6'
```

**Comment by Izmenoff** [comment]
[appadmin@srv-mncacti-02 scripts]$ cd /var/www/html/cacti/
[appadmin@srv-mncacti-02 cacti]$ php scripts/ss_host_disk.php 'srv-omi-01' '366' '2:161:500:1:40:public::::::' 'get' 'used' '6'
say nothing
in log

20-Jan-2018 14:09:50 - PHPSVR WARNING: Function does not exist INC: 'ss_host_disk.php' FUNC: ''srv-omi-01'' PARMS: ''366' '2:161:500:1:40:public::::::' 'get' 'used' '6''
--
20-Jan-2018 14:09:37 - PHPSVR WARNING: Script Server terminated with signal '2' in file:'', function:'', params:''

**Comment by netniV** [comment]
If nothing is being output by the first part, that would suggest that you don't any output coming back from that device.  For the script server part, I missed adding the function to the last part, so it should read:

```
/var/www/html/cacti/scripts/ss_host_disk.php ss_host_disk 'srv-omi-01' '366' '2:161:500:1:40:public::::::' 'get' 'used' '6'
```

Have you definitely enabled SNMP on that device?  If you edit the device in question, does it show SNMP Error top left?

One other thing to check, can you actually ping srv-omi-01? If that doens't resolve to an IP that may be a problem.

**Comment by cigamit** [comment]
We should see a screen shot of the poller cache for the system with these queries highlighted.  The syntax of the script server is:

`/path/to/stript.php function_to_call option1 ... optionN`

It does not look like it's being called properly, which might mean that for this script someone has changed the Data Input method from Script Server (PHP) to Script.  That is my guess.  If that is the case, it's a two step repair:

1) Change from Script to Script Server
2) Repopulate the Poller Cache

**Comment by cigamit** [comment]
Stet the data input method.  It's a Data Query.  So, here are what the Data Query edit and the Resource XML files should look like.

![hostdiskdataquery](https://user-images.githubusercontent.com/957322/35184452-992436aa-fdbb-11e7-976e-8ce7b615d1f4.PNG)

![hostdiskdataqueryresourcexml](https://user-images.githubusercontent.com/957322/35184457-9ee9e4c2-fdbb-11e7-8a93-c7808534cbc2.PNG)

**Comment by cigamit** [comment]
My guess is that on the first image, you just have the wrong Data Input Method.

**Comment by Izmenoff** [comment]
I have 2 cacti servers and after updated to 1.1.31 I see the same problems with graphs on different linux machines which uses default template. Gpraphs on HPUX servers and Network devices works fine.
I have changed Data Input Method to Get Script Server Data (Indexed), but it doesn,t help.
All devices ping and SNMP is ok

[appadmin@srv-mncacti-02 ~]$ sudo php /var/www/html/cacti/scripts/ss_host_disk.php ss_host_disk 'srv-omi-01' '366' '2:161:500:1:40:public::::::' 'get' 'used' '6'
[appadmin@srv-mncacti-02 ~]$
say nothing

22-Jan-2018 09:18:47 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
thrown in file: /usr/share/cacti/scripts/ss_net_snmp_disk_bytes.php on line: 23
#1 {main}
#0 /usr/share/cacti/script_server.php(221): ss_net_snmp_disk_bytes()
Stack trace:
22-Jan-2018 09:18:47 - ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function ss_net_snmp_disk_bytes(), 0 passed in /usr/share/cacti/script_server.php on line 221 and exactly 1 expected in /usr/share/cacti/scripts/ss_net_snmp_disk_bytes.php:23

about /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php
 - it doesn't matter, I have to repair my default template for

**Comment by Izmenoff** [comment]
after create new device and grpahs

2018-01-31 10:08:02 - SPINE: Poller[1] WARNING: Invalid Response(s), Errors[3] Device[cacti] Thread[1] Graphs[cacti - Logged in Users, cacti - Logged in Users] Graphs[cacti - Disk Space - /dev/mapper/vg00-lv_usr, cacti - Disk Space - /dev/mapper/vg00-lv_usr] Graphs[cacti - Disk Space - /dev/mapper/vg01-lv_var_opt, cacti - Disk Space - /dev/mapper/vg01-lv_var_opt] DS[27562, 27567, 27572]
--
31-Jan-2018 10:07:50 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1249 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'data_input_field_id' cannot be null
31-Jan-2018 10:07:50 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO data_input_data (data_input_field_id,data_template_data_id,t_value,value) VALUES (?, ?, "", ?)'
31-Jan-2018 10:07:50 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1249 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - ERROR PHP NOTICE: Undefined index: output_type in file: /usr/share/cacti/lib/template.php on line: 1249
31-Jan-2018 10:07:50 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1243 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'data_input_field_id' cannot be null
31-Jan-2018 10:07:50 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO data_input_data (data_input_field_id,data_template_data_id,t_value,value) VALUES (?, ?, "", ?)'
31-Jan-2018 10:07:50 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1243 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - ERROR PHP NOTICE: Undefined index: index_value in file: /usr/share/cacti/lib/template.php on line: 1243
31-Jan-2018 10:07:50 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1237 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'data_input_field_id' cannot be null
31-Jan-2018 10:07:50 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO data_input_data (data_input_field_id, data_template_data_id, t_value, value) VALUES (?, ?, "", ?)'
31-Jan-2018 10:07:50 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1237 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - ERROR PHP NOTICE: Undefined index: index_type in file: /usr/share/cacti/lib/template.php on line: 1237
31-Jan-2018 10:07:50 - CMDPHP SQL Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1249 db_execute_prepared)(/lib/database.php: 208 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - CMDPHP ERROR: A DB Exec Failed!, Error: Column 'data_input_field_id' cannot be null
31-Jan-2018 10:07:50 - DBCALL ERROR: A DB Exec Failed!, Error:1048, SQL:'REPLACE INTO data_input_data (data_input_field_id,data_template_data_id,t_value,value) VALUES (?, ?, "", ?)'
31-Jan-2018 10:07:50 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 37 form_save)(/graphs_new.php: 131 host_new_graphs_save)(/graphs_new.php: 259 create_complete_graph_from_template)(/lib/template.php: 1249 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
31-Jan-2018 10:07:50 - ERROR PHP NOTICE: Undefined index: output_type in file: /usr/share/cacti/lib/template.php on line: 1249

**Comment by cigamit** [comment]
Open mysql as a root user and post the output of the following command

`show global variables like 'sql_mode';`

**Comment by Izmenoff** [comment]
MariaDB [(none)]> show global variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                     |
+---------------+-------------------------------------------------------------------------------------------+
| sql_mode      | STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------+

**Comment by cigamit** [comment]
Edit /etc/my.cnf.d/server and change to the to the following:

`sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Then, restart MariaDB.  After that, if it's a newish install, you should re-install.

**Comment by Izmenoff** [comment]
I did it, but graphps is empty (local linux machine). 
Another devices\graphs (Interface - Traffic (bits/sec) ) works good.
![image](https://user-images.githubusercontent.com/17400240/35790591-388c0214-0a54-11e8-940e-5dba7e5d7dd6.png)

**Comment by netniV** [comment]
when you edit the local device, what does the SNMP information say top left?

**Comment by Izmenoff** [comment]
Device is cacti server. SNMP say ok.
But it doesn't matter. All of linux servers at my network have the same problem with default templates  (Linux local machine, Generic or Net-SNMP Device). Also after create graphs I see strange errors from another one template Cisco WLS. If I delete graphs with templates (Linux local machine, Generic or Net-SNMP Device) log file will be without Cisco WLS errors!

05-Feb-2018 14:15:02 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Cipher.php: 17 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
05-Feb-2018 14:15:02 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Cipher.php on line: 17
05-Feb-2018 14:15:02 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Cipher.php: 16 CactiErrorHandler)(/lib/functions.php: 4482 cacti_debug_backtrace)
05-Feb-2018 14:15:02 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Cipher.php on line: 16
05-Feb-2018 14:15:01 - POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues: 3, Graphs[cacti - Disk Space - /dev/mapper/vg01-lv_www, cacti - Disk Space - /dev/mapper/vg01-lv_www] Graphs[cacti - Disk Space - /dev/mapper/vg00-lv_root, cacti - Disk Space - /dev/mapper/vg00-lv_root] Graphs[cacti - Load Average, cacti - Load Average] DS[27867, 27862, 27857]

**Comment by netniV** [comment]
OK, so if we work backwards from this, it would suggest you have a template problem.  Something isn't linking up right with that template.  Now, I could go through all the steps to work out exactly what, but instead I'm going to suggest that you try to import the Local_Linux_Machine.xml.gz file using the following steps:

- Download the .gz file from &lt;cacti&gt;/install/templates/Local_Linux_Machine.xml.gz
- Browse to `Console -> Import/Export -> Import Templates`
- Click on `Select a File` which may not even appear to be a button (see my screen shot below) but does still work and select the downloaded .gz file
- Tick `Preview Import Only`
- Click on Import

This should run through all the steps of importing the template but give output about what would have changed if anything.  Copy and paste that output here.

![image](https://user-images.githubusercontent.com/9052188/35807473-cce8fc8e-0a7a-11e8-9675-8462e06c10e5.png)

**Comment by cigamit** [comment]
Actually, the Local_Linux_Machine.xml.gz is a Cacti package imported using the CLI script import_package.php.  I suspect that the other Template, the Cisco one, may be the one damaged.  It should also be re-imported, though with the Import process as described above.

Once the package plugin is published, so long as the web server has certain write permissions, that plugin will also be able to import that packages.

**Comment by netniV** [comment]
Oh yeah, I keep forgetting the import on the web isn't for packages.

**Comment by Izmenoff** [comment]
Thanks a lot for your help!
I have installed that, but after create a new local linux device I get errors with other CISCO WLC template and haven't any graphs.
![image](https://user-images.githubusercontent.com/17400240/35843936-f6a36554-0b1b-11e8-9135-de8091bb45e8.png)
If I create device as Net-SNMP Device, part of graphs is ok. Only problem graphs which use Data Queries SNMP - Get Mounted Partitions (Available Disk Space). All of them not working and I see this errors:
![image](https://user-images.githubusercontent.com/17400240/35844036-5e2065ec-0b1c-11e8-9f7a-2571aeaf3237.png)

**Comment by cigamit** [comment]
Can you upload your template xml and resource xml?

**Comment by Izmenoff** [comment]
Do you mean Cisco template?  There is - https://forums.cacti.net/viewtopic.php?f=12&t=43852
If you mean Cacti templates there is all default. When I update Cacti, I replace all files.
I can send to you my database file (MariaDB). Maybe It will resolve the problem.
Thanks!

**Comment by cigamit** [comment]
The issue with this template, the one on the first post, is that there are unmet dependencies.  I'm going to look into it just a big long, but when you import, you will see the following:

![ciscowlcissues](https://user-images.githubusercontent.com/957322/35946911-367678b4-0c2b-11e8-87db-6ff947d28fa4.PNG)

Please confirm by re-importing it yourself.

**Comment by cigamit** [comment]
Then, retry importing this version.  It might server you better.  Please let us know.


[cacti_host_template_cisco_wlc_-_5508.zip](https://github.com/Cacti/cacti/files/1705131/cacti_host_template_cisco_wlc_-_5508.zip)

**Comment by cigamit** [comment]
Also, the following should be updated.  I have not audited the whole thing, but it calls some deprecated stuff.

[Cisco_WLC_Radios.zip](https://github.com/Cacti/cacti/files/1705142/Cisco_WLC_Radios.zip)

**Comment by cigamit** [comment]
Lastly, though this thing should technically work, it's written in such a way that if you were to ever require snmpv3, it would have to be rewritten.

**Comment by cigamit** [comment]
If all this works, you should upload this information into the forums so that others can benefit from the updates.  Thanks!

**Comment by Izmenoff** [comment]
Yes, I have the same result:
![image](https://user-images.githubusercontent.com/17400240/35957857-c3e7b8ba-0cae-11e8-97f8-dae964b28e26.png)
Afetr import new template the results seems good.  But after create a new graphs use Data Queries SNMP - Get Mounted Partitions (Available Disk Space):
![image](https://user-images.githubusercontent.com/17400240/35958155-5b955446-0cb0-11e8-8991-7f9e87f17b65.png)
After create a new device with template local linux machine:
![image](https://user-images.githubusercontent.com/17400240/35958196-8fa45656-0cb0-11e8-84f4-7d1fa8a92ea4.png)

**Comment by cigamit** [comment]
You need to upload your poller screen shot from the items of issue.  Is this a new install that you are testing on?  Also, please run spine from the command line as follows:

`./spine -R -V 3 -S -f host_id -l host_id`

Have the host_id be the id of the problem host.  Please upload ASAP.  Thanks!

**Comment by Izmenoff** [comment]
Cacti ver 1.1.34. I just time to time update it via overwrite all files and after that run upgrade wizard .
The issue doesn't depend on host. I have a lot of linux servers and problem the same on all of them. I even can't get partitions information of server where cacti installed. I also have old Cacti  0.8.8b and there is woks good.
I found oldest template https://docs.cacti.net/usertemplate:host:linux:generic and it's working for me.
Strange things with default template for linux...

**Comment by cigamit** [comment]
This issue should be resolved now.  However, before you re-import the template, I would like you to manually run the 3 delete statements in the install/updates/1_1_35.php script.

Then, re-import the Cisco Device Template and it should be clean.  You poller should run clean as well.

**Comment by Izmenoff** [comment]
I updated Cacti to 1.1.35 and re-imported cacti_host_template_cisco_wlc_-_5508.zip
But still not working..
![image](https://user-images.githubusercontent.com/17400240/36085754-3b6772e0-0fd9-11e8-86ef-fdaf6090df7f.png)

**Comment by cigamit** [comment]
Well, we are making progress.  Now we have to fix whatever is generating that stack trace, that output is going to standard output, which is causing many, but not all those errors.  Can you research that?  Start by looking up how to test the script server.  Also, do you have plugins installed?  one of those sql errors looks troubling, like not poller related.

**Comment by cigamit** [comment]
Lastly, I had asked for some output a post or so ago, please provide it.

**Comment by Izmenoff** [comment]
I have only a Thold 1.0.3 plugin. What kinde of test script server I should run?

[appadmin@srv-mncacti-02 bin]$ ./spine -R -V 3 -S -f host_id -l host_id
SPINE: Using spine config file [../etc/spine.conf]
SPINE: Version 1.1.35 starting
NOTE: Spine will support multithread device polling.
DEBUG: Initial Value of Active Threads is 0
SPINE: The Final Value of Threads is 0
Time: 0.0507 s, Threads: 20, Devices: 0

**Comment by cigamit** [comment]
Jeez, replace host_id with the host_id not the word 'host_id'.  Secondly, I asked you for your poller cache output for the device in question.  Do you not know how to capture that screen shot?  Lastly, search google using the following string, for testing script server "testing script server site:cacti.net".

**Comment by cigamit** [comment]
Also, what OS is this?  Can you check your php.ini files for 'display_errors' and see what it is set to.  If 'on', set to 'off' and restart the apache.

**Comment by cigamit** [comment]
Also, disable xdebug.  I think that is who is creating the stack traces.  https://stackoverflow.com/questions/6911897/disable-html-stack-traces-by-xdebug

**Comment by Izmenoff** [comment]
CentOS Linux release 7.4.1708, 10.2.12-MariaDB, PHP Version  7.1.13
'display_errors'  has been off

about -disable xdebug-
Shall I place this in php.ini ?
php_flag xdebug.default_enable Off
php_flag xdebug.overload_var_dump Off
php_flag xdebug.show_exception_trace Off
php_value xdebug.trace_format 1


strange things - a template local linux machine use a script of cisco wlc template
![image](https://user-images.githubusercontent.com/17400240/36096372-29c73628-1007-11e8-92b6-c94a5114fa74.png)

**Comment by cigamit** [comment]
Well that's better.  That first set of poller cache was contributing to the issue.  Yes, however you do it, disable xdebug.  The scripts should be updated as well to ensure this is at near the top of every file:

`error_reporting(0);`

This is especially true for the script server.  After that, your log may still have those host_id IN() errors, which is separate and will have to be researched.

**Comment by netniV** [comment]
With us changing the error handler, should we still be setting error_reporting(0) ?  That will suppress all errors from appearing.  The above argument error seems to be a common error, as I've an open issue on one of my templates where the script server doesn't seem to be sending over the function name when it should.  

I've tried to debug it but I've not found the reason why it isn't putting the name in despite it being in the template file (https://github.com/netniV/cisco-sfp/issues/1).  It may be that I've just been looking at it too long and missed the obviously.

**Comment by Izmenoff** [comment]
Thanks a lot!
Is there another way to resolve the problem?
![image](https://user-images.githubusercontent.com/17400240/36098796-596646e4-1011-11e8-8f9b-db168030e387.png)

**Comment by cigamit** [comment]
@netniV, until we have the issue in hand, it was the easiest way to remove the issues.  It's not that it's not a back practice.  But those stack traces were appearing in the log which kind of worried me.  They should not be.,

@Izmenoff,

Much better.  I do not think that these are related to this issue.  I will search the code this morning before my day starts.

**Comment by netniV** [comment]
@cigamit  Yes, what I'm trying to say is I have the same issues with very similar backtraces (only change i the function name and script it was calling) appearing when they shouldn't (see above issue).

**Comment by cigamit** [comment]
@netniV, 

Yup.

@Izmenoff,

I'm suspecting it's realtime.  It's the only real piece of code that stuck out.  I've updated cmd_realtime.php with some instrumentation.  Can you update please.

**Comment by cigamit** [comment]
I just took a second look and made one more change.

**Comment by cigamit** [comment]
And another update.  This other final(?) issue should be solved now.

**Comment by Izmenoff** [comment]
**cigamit**, Thanks a lot!!!  
Changes in cmd_realtime.php solved the problem. Now log is clear.
![image](https://user-images.githubusercontent.com/17400240/36134407-b5d56a8e-1095-11e8-8afd-6dd1c6523fe1.png)
