### ISSUE TITLE
Too few arguments to function dsv_log

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#4462]
After updating from 1.2.19 release to 1.2.x today
```
2021/11/14 00:00:39 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2021/11/14 00:00:39 - ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function dsv_log(), 1 passed in /var/www/localhost/htdocs/cacti/lib/functions.php on line 1739 and exactly 2 expected in /var/www/localhost/htdocs/cacti/lib/functions.php:1700 Stack trace: #0 /var/www/localhost/htdocs/cacti/lib/functions.php(1739): dsv_log('test_data_sourc...') #1 /var/www/localhost/htdocs/cacti/lib/api_automation.php(2642): test_data_sources('3', '1139', '1', '71') #2 /var/www/localhost/htdocs/cacti/lib/api_automation.php(2230): create_dq_graphs('1139', '1', Array) #3 /var/www/localhost/htdocs/cacti/lib/data_query.php(390): automation_execute_data_query('1139', '1') #4 /var/www/localhost/htdocs/cacti/poller_commands.php(144): run_data_query('1139', '1') #5 {main} thrown in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 1700
```

**Comment by netniV** [comment]
Thanks JD I'll take a look

**Comment by netniV** [comment]
The patch should fix this

**Comment by jdcoats** [comment]
Thanks!
