### ISSUE TITLE
Cacti 1.1.30  Issue - Unix Get Mounted Partitions issue

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/cacti#1170]
Total: 0, Delta: 0, Running data query [2].
Total: 0, Delta: 0, Found type = '1' [Script/Command].
Total: 0, Delta: 0, Unknown type = '1'
Total: 0, Delta: 0, Found data query XML file at '/usr/share/cacti/resource/script_queries/unix_disk.xml'
Total: 0, Delta: 0, Update data query sort cache complete
Total: 0.01, Delta: 0, Updated data query index ordering
Total: 0.01, Delta: 0.01, Update re-index cache complete
Total: 0.01, Delta: 0, Update graph data query cache complete
Total: 0.01, Delta: 0, Update data source data query cache complete
Total: 0.01, Delta: 0, Update data query cache complete
Total: 0.01, Delta: 0, Update poller cache from query complete
Total: 0.01, Delta: 0, Automation execute data query complete
Total: 0.01, Delta: 0, Plugin hooks complete
Total: 0, Delta: 0, Found data query XML file at '/usr/share/cacti/resource/snmp_queries/interface.xml'
Total: 0.01, Delta: 0.01, Found data query XML file at '/usr/share/cacti/resource/script_queries/unix_disk.xml'
Total: 0, Delta: 0, Running data query [2].
Total: 0, Delta: 0, Found type = '1' [Script/Command].
Total: 0, Delta: 0, Unknown type = '1'
Total: 0, Delta: 0, Found data query XML file at '/usr/share/cacti/resource/script_queries/unix_disk.xml'

logfile
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'total' '16''
--
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'total' '60''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'used' '16''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'used' '60''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'total' '11''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'total' '38''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope test] ERROR: Empty result [10.17.0.37]: '/usr/share/cacti/scripts/ss_host_disk.php '10.17.0.37' '294' '2:161:500:1:20:public::::::' 'get' 'total' '62''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'used' '11''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'used' '38''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope test] ERROR: Empty result [10.17.0.37]: '/usr/share/cacti/scripts/ss_host_disk.php '10.17.0.37' '294' '2:161:500:1:20:public::::::' 'get' 'used' '62''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'total' '6''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'total' '7''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'used' '6''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[HP SiteScope] ERROR: Empty result [srv-hpss-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-hpss-01' '357' '2:161:500:1:40:public::::::' 'get' 'used' '7''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_cpu.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'usage' '3''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'total' '49''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'used' '49''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'total' '44''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'used' '44''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'total' '39''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'used' '39''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'total' '31''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'used' '31''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'total' '1''
2018-01-04 10:50:43 - SPINE: Poller[1] Device[ZTE Minos new] ERROR: Empty result [srv-nnems-01]: '/usr/share/cacti/scripts/ss_host_disk.php 'srv-nnems-01' '356' '2:161:500:1:40:public::::::' 'get' 'used' '1''
04-Jan-2018 10:50:43 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4472 cacti_debug_backtrace)
thrown in file: /usr/share/cacti/scripts/ss_net_snmp_disk_bytes.php on line: 23
#1 {main}
#0 /usr/share/cacti/script_server.php(221): ss_net_snmp_disk_bytes()
Stack trace:
04-Jan-2018 10:50:43 - ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function ss_net_snmp_disk_bytes(), 0 passed in /usr/share/cacti/script_server.php on line 221 and exactly 1 expected in /usr/share/cacti/scripts/ss_net_snmp_disk_bytes.php:23

**Comment by Izmenoff** [comment]
rollback to 1.1.29 and works fine

**Comment by netniV** [comment]
Try running `/usr/share/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'total' '16'` at the comment line and see if any other messages are displayed.

**Comment by Izmenoff** [comment]
I rolled back to 1.1.29

**Comment by netniV** [comment]
You actually have two different errors occurring in this log.  ss_host_disk.php is apparently not returning any values, or at least not what is expected.  ss_net_snmp_disk_bytes.php is expect a host id to be passed and thinks no id was passed.

**Comment by Izmenoff** [comment]
it happend after update from 1.1.29 - 1.1.30
problem with ss_host_disk.php, ss_host_cpu.php etc from templates local linux machine, net snmp device.
After create a new device I see
POLLER: Poller[1] WARNING: Poller Output Table not Empty. Issues: 3, Graphs[cacti - Disk Space - /dev/mapper/vg01-lv_www, cacti - Disk Space - /dev/mapper/vg01-lv_www] Graphs[cacti - Disk Space - /dev/mapper/vg00-lv_log, cacti - Disk Space - /dev/mapper/vg00-lv_log] Graphs[cacti - Memory Usage, cacti - Memory Usage] DS[27746, 27741, 27736]

2018-01-26 14:58:27 - SPINE: Poller[1] Device[U2000] ERROR: Empty result [10.18.23.13]: '/var/www/html/cacti/scripts/ss_host_disk.php '10.18.23.13' '311' '2:161:500:1:40:public::::::' 'get' 'used' '4''
--
2018-01-26 14:58:27 - SPINE: Poller[1] Device[MAXIMO izmir01 # Application 10.16.1.42] ERROR: Empty result [10.16.1.42]: '/var/www/html/cacti/scripts/ss_host_disk.php '10.16.1.42' '8' '2:161:500:1:20:public::::::' 'get' 'total' '8''
2018-01-26 14:58:27 - SPINE: Poller[1] Device[MAXIMO izmir01 # Application 10.16.1.42] ERROR: Empty result [10.16.1.42]: '/var/www/html/cacti/scripts/ss_host_disk.php '10.16.1.42' '8' '2:161:500:1:20:public::::::' 'get' 'used' '8''
26-Jan-2018 14:58:27 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4520 cacti_debug_backtrace)
thrown in file: /var/www/html/cacti/scripts/ss_net_snmp_disk_bytes.php on line: 23
#1 {main}
#0 /var/www/html/cacti/script_server.php(221): ss_net_snmp_disk_bytes()
Stack trace:
26-Jan-2018 14:58:27 - ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function ss_net_snmp_disk_bytes(), 0 passed in /var/www/html/cacti/script_server.php on line 221 and exactly 1 expected in /var/www/html/cacti/scripts/ss_net_snmp_disk_bytes.php:23
